const express = require('express');
const postsService = require('./postsService.js');

const postsRouter = express.Router();
const jsonParser = express.json();

// postsRouter
//   .route('/users/:userId/posts')
//   .get((req, res) => {

//   })

postsRouter
  .route('/:postId')
  .delete((req, res) => {
    db = req.app.get('db');
    postsService.deletePost(db, req.params.postId)
      .then(res.send(200));
  })

module.exports = postsRouter;

// CREATE TABLE posts (
//   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//   title TEXT NOT NULL,
//   url TEXT NOT NULL,
//   location TEXT,
//   notes TEXT,
//   rating INTEGER DEFAULT 1,
//   date_created TIMESTAMPTZ DEFAULT now(),
//   user_id INTEGER REFERENCES users NOT NULL
// );