const express = require('express');
const postsService = require('./postsService.js');

const postsRouter = express.Router();
const jsonParser = express.json();

// postsRouter.route('/')

module.exports = postsRouter;

// CREATE TABLE posts (
//   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
//   title TEXT NOT NULL,
//   url TEXT NOT NULL,
//   location TEXT,
//   notes TEXT,
//   rating INTEGER DEFAULT 1,
//   date_created TIMESTAMPTZ DEFAULT now(),
//   user_id INTEGER REFERENCES users NOT NULL
// );